services:  
  - type: web  
    name: asesorbot  
    env: python  
    region: oregon  
    plan: free  
    buildCommand: "pip install -r requirements.txt"  
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"  
    envVars:  
      - key: TELEGRAM_TOKEN  
        fromSecret: TELEGRAM_TOKEN  
      - key: YOUR_TELEGRAM_ID  
        fromSecret: YOUR_TELEGRAM_ID  
      - key: TASA_BCV  
        value: "119.40"  
    healthCheckPath: /healthz  
